apiVersion: apps/v1
kind: Deployment
metadata:
  name: ham-exam-db-dep
  namespace: ham-exam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ham-exam-db

  template:
    metadata:
      labels:
        app: ham-exam-db
    spec:
      containers:
      - name: ham-exam-postgres
        image: tjwalkr3/ham-exam-db:$CONTAINER_VERSION
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "chatuser"
        - name: POSTGRES_PASSWORD
          value: "chatpassword"
        - name: POSTGRES_DB
          value: "chatdb"

---

apiVersion: v1
kind: Service
metadata:
  name: ham-exam-db-svc
  namespace: ham-exam
spec:
  selector:
    app: ham-exam-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
